version: '3.7'

services:

  web:
    container_name: drf-api-project
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .:/code

  celery-worker:
    container_name: celery-worker-1
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - web

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - web
      - celery-worker

